Blog app - controllers
AliShahSafdari/blog-app pull request #4
Opened 2023-08-21 14:11 UTC by AliShahSafdari

In this PR I do the following:

- A route.
- Action in the correct controller.
- A view file.
- View files should include only placeholders written in plain HTML, e.g:
- list of posts for a given user
- Create handle only the 4 required URLs.

2023-08-21 14:30 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @AliShahSafdari,

Good job so far!
✔️ Use of nested routes
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-21 14:30 UTC, TedLivist commented on app/controllers/posts_controller.rb
> +class PostsController < ActionController::Base
- [ ] This controller should inherit from the `ApplicationController`, not `ActionController::Base`. Kindly fix this.

2023-08-21 14:30 UTC, TedLivist commented on app/controllers/users_controller.rb
> +class UsersController < ActionController::Base
- [ ] This controller should inherit from the `ApplicationController`, not `ActionController::Base`. Kindly fix this.

2023-08-21 14:30 UTC, TedLivist commented on app/controllers/comments_controller.rb
> +end
- [ ] There is really no point in having this comment controller, since it has not corresponding routes. I would recommend you stick to the posts and users controllers required for this project. Kindly remove this controller.

2023-08-21 14:30 UTC, TedLivist commented on app/controllers/likes_controller.rb
> +end
- [ ] There is really no point in having this likes controller, since it has not corresponding routes. I would recommend you stick to the posts and users controllers required for this project. Kindly remove this controller.

2023-08-21 14:30 UTC, TedLivist commented on app/views/comments/edit.html.erb
> +<h1> edit a commment in post</h1>
- [ ] Kindly remove all the **comments** and **likes** views folders. They have no corresponding routes or controller actions, so there is no point in creating them.

  ![image](https://github.com/AliShahSafdari/blog-app/assets/36542986/1f96c473-24dd-4a2d-bc9d-679fe76197f4)

2023-08-21 14:30 UTC, TedLivist commented on app/views/posts/edit.html.erb
> +<h1> edit a post</h1>
- [ ] Kindly remove the **edit** and **new** view files in the posts and users views directories. They have no routes or controllers for them, so they are mostly useless. Kindly remove them.

  ![image](https://github.com/AliShahSafdari/blog-app/assets/36542986/cfbd2b5a-599f-49fb-b740-bc7389a18f19)

2023-08-21 16:55 UTC, AliShahSafdari commented on app/controllers/posts_controller.rb
> +class PostsController < ActionController::Base
Thanks

2023-08-21 16:55 UTC, AliShahSafdari commented on app/views/posts/edit.html.erb
> +<h1> edit a post</h1>
Remove extra file

2023-08-21 17:19 UTC, rloterh requested changes
Hi Ali, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 
🚦 _ 🏡 🏃‍♂️ 🏚️ 🌴 🗼

## Highlights 👍  
- Good job so far improving upon the Controller and related routes and views.
- ReadMe looks great!

## Required Changes ♻️
_Kindly check the inline comments under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-21 17:19 UTC, rloterh commented on app/controllers/posts_controller.rb
> +end
- [ ] Let's ensure that `PostController` inherits from `ApplicationController`, not `ActionController`, and our `PostController` class should be similar to:

```ruby
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index; end

  def show; end

end
```

2023-08-21 17:19 UTC, rloterh commented on app/controllers/users_controller.rb
> +end
- [ ] Similarly, the `UserController`  should inherits from `ApplicationController`, and our `UserController` class should be similar to:

```ruby
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index; end

  def show; end

end
```

2023-08-21 17:19 UTC, rloterh commented on app/controllers/comments_controller.rb
> +end
- [ ] Kindly ensure to remove the CommentsController, like indicated in the previous review.

2023-08-21 17:19 UTC, rloterh commented on app/controllers/likes_controller.rb
> +end
- [ ] Kindly ensure to remove the LikesController, like indicated in the previous review.

2023-08-21 17:19 UTC, rloterh commented on app/views/posts/edit.html.erb
> +<h1> edit a post</h1>
well resolved! ✔️

2023-08-21 17:19 UTC, rloterh commented on app/views/comments/edit.html.erb
> +<h1> edit a commment in post</h1>
well resolved! ✔️

2023-08-21 17:19 UTC, rloterh commented on app/controllers/likes_controller.rb
> +end
Can be improved!

2023-08-21 17:19 UTC, rloterh commented on app/controllers/comments_controller.rb
> +end
Can be improved!

2023-08-21 17:19 UTC, rloterh commented on app/controllers/users_controller.rb
> +class UsersController < ActionController::Base
Can be improved!

2023-08-22 07:47 UTC, rloterh commented on app/controllers/posts_controller.rb
> +end
well resolved! ✔️

2023-08-22 07:47 UTC, rloterh commented on app/controllers/users_controller.rb
> +end
well resolved! ✔️

2023-08-22 07:47 UTC, rloterh commented on app/controllers/comments_controller.rb
> +end
well resolved! ✔️

2023-08-22 07:47 UTC, rloterh commented on app/controllers/likes_controller.rb
> +end
well resolved! ✔️

2023-08-22 07:53 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Ali,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Controller and corresponding routes and views properly added!
🎲 Rails naming convention observed!

Cheers..Happy coding!💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-22 07:59 UTC, merged